[bqf]
fetch.github = "kevinhwang91/nvim-bqf"
src.git = "https://github.com/kevinhwang91/nvim-bqf"
passthru.as = "bqf"

[catppuccin]
fetch.github = "catppuccin/nvim"
src.git = "https://github.com/catppuccin/nvim"
passthru.as = "catppuccin"

[chai-nvim]
fetch.github = "comfysage/chai.nvim"
src.git = "https://github.com/comfysage/chai.nvim"
passthru.as = "chai"
passthru.start = "true"

[cloak]
fetch.github = "laytan/cloak.nvim"
src.git = "https://github.com/laytan/cloak.nvim"
passthru.as = "cloak"

[crates]
fetch.github = "saecki/crates.nvim"
src.git = "https://github.com/saecki/crates.nvim"
passthru.as = "crates"

[direnv]
fetch.github = "NotAShelf/direnv.nvim"
src.git = "https://github.com/NotAShelf/direnv.nvim"
passthru.as = "direnv"

[evergarden]
fetch.github = "everviolet/nvim"
src.git = "https://github.com/everviolet/nvim"
passthru.as = "evergarden"

[fidget]
fetch.github = "j-hui/fidget.nvim"
src.git = "https://github.com/j-hui/fidget.nvim"
src.branch = "legacy"
passthru.as = "fidget"

[freeze]
fetch.github = "charm-community/freeze.nvim"
src.git = "https://github.com/charm-community/freeze.nvim"
passthru.as = "freeze"

[fzf-lua]
fetch.github = "ibhagwan/fzf-lua"
src.git = "https://github.com/ibhagwan/fzf-lua"
passthru.as = "fzf"

[keymaps-nvim]
fetch.github = "comfysage/keymaps.nvim"
src.git = "https://github.com/comfysage/keymaps.nvim"
passthru.as = "keymaps"

[lylla-nvim]
fetch.github = "comfysage/lylla.nvim"
src.git = "https://github.com/comfysage/lylla.nvim"
passthru.as = "lylla"

[lynn-nvim]
fetch.github = "comfysage/lynn.nvim"
src.git = "https://github.com/comfysage/lynn.nvim"
passthru.start = "true"
passthru.as = "lynn"

[marks-nvim]
fetch.github = "chentoast/marks.nvim"
src.git = "https://github.com/chentoast/marks.nvim"
passthru.as = "marks"

[mini-ai]
fetch.github = "echasnovski/mini.ai"
src.git = "https://github.com/echasnovski/mini.ai"

[mini-align]
fetch.github = "echasnovski/mini.align"
src.git = "https://github.com/echasnovski/mini.align"

[mini-bracketed]
fetch.github = "echasnovski/mini.bracketed"
src.git = "https://github.com/echasnovski/mini.bracketed"

[mini-diff]
fetch.github = "echasnovski/mini.diff"
src.git = "https://github.com/echasnovski/mini.diff"

[mini-files]
fetch.github = "echasnovski/mini.files"
src.git = "https://github.com/echasnovski/mini.files"

[mini-git]
fetch.github = "echasnovski/mini-git"
src.git = "https://github.com/echasnovski/mini-git"

[mini-icons]
fetch.github = "echasnovski/mini.icons"
src.git = "https://github.com/echasnovski/mini.icons"

[mini-jump2d]
fetch.github = "echasnovski/mini.jump2d"
src.git = "https://github.com/echasnovski/mini.jump2d"

[mini-move]
fetch.github = "echasnovski/mini.move"
src.git = "https://github.com/echasnovski/mini.move"

[mini-operators]
fetch.github = "echasnovski/mini.operators"
src.git = "https://github.com/echasnovski/mini.operators"

[mini-pairs]
fetch.github = "echasnovski/mini.pairs"
src.git = "https://github.com/echasnovski/mini.pairs"

[mini-splitjoin]
fetch.github = "echasnovski/mini.splitjoin"
src.git = "https://github.com/echasnovski/mini.splitjoin"

[mini-surround]
fetch.github = "echasnovski/mini.surround"
src.git = "https://github.com/echasnovski/mini.surround"

[mini-trailspace]
fetch.github = "echasnovski/mini.trailspace"
src.git = "https://github.com/echasnovski/mini.trailspace"

[mossy-nvim]
fetch.github = "comfysage/mossy.nvim"
src.git = "https://github.com/comfysage/mossy.nvim"
passthru.as = "mossy"

[neogen]
fetch.github = "danymat/neogen"
src.git = "https://github.com/danymat/neogen"

[neo-tree]
fetch.github = "nvim-neo-tree/neo-tree.nvim"
src.git = "https://github.com/nvim-neo-tree/neo-tree.nvim"
passthru.as = "neo-tree"

[nivvie-nvim]
fetch.github = "comfysage/nivvie.nvim"
src.git = "https://github.com/comfysage/nivvie.nvim"
passthru.as = "nivvie"

[nui]
fetch.github = "MunifTanjim/nui.nvim"
src.git = "https://github.com/MunifTanjim/nui.nvim"
passthru.as = "nui"

[nvim-lint]
fetch.github = "mfussenegger/nvim-lint"
src.git = "https://github.com/mfussenegger/nvim-lint"
passthru.as = "lint"

[nvim-nio]
fetch.github = "nvim-neotest/nvim-nio"
src.git = "https://github.com/nvim-neotest/nvim-nio"
passthru.as = "nio"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
src.git = "https://github.com/neovim/nvim-lspconfig"
passthru.start = "true"
passthru.as = "lspconfig"

[nvim-treesitter]
fetch.github = "nvim-treesitter/nvim-treesitter"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"
src.branch = "main"
passthru.start = "true"
passthru.as = "treesitter"

[nvim-treesitter-context]
fetch.github = "nvim-treesitter/nvim-treesitter-context"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter-context"
passthru.as = "treesitter-context"

[plenary]
fetch.github = "nvim-lua/plenary.nvim"
src.git = "https://github.com/nvim-lua/plenary.nvim"
passthru.start = "true"
passthru.as = "plenary"

[quill-nvim]
fetch.github = "comfysage/quill.nvim"
src.git = "https://github.com/comfysage/quill.nvim"
passthru.as = "quill"

[rainbow-delimiters]
fetch.github = "hiphish/rainbow-delimiters.nvim"
src.git = "https://github.com/hiphish/rainbow-delimiters.nvim"
passthru.as = "rainbow-delimiters"

[sayama-nvim]
fetch.github = "comfysage/sayama.nvim"
src.git = "https://github.com/comfysage/sayama.nvim"
passthru.as = "sayama"

[schemastore]
fetch.github = "b0o/schemastore.nvim"
src.git = "https://github.com/b0o/schemastore.nvim"
passthru.as = "schemastore"

[shelf-nvim]
fetch.github = "comfysage/shelf.nvim"
src.git = "https://github.com/comfysage/shelf.nvim"
passthru.as = "shelf"

[symbol-usage]
fetch.github = "Wansmer/symbol-usage.nvim"
src.git = "https://github.com/Wansmer/symbol-usage.nvim"
passthru.as = "symbol-usage"

[tabby-nvim]
fetch.github = "nanozuki/tabby.nvim"
src.git = "https://github.com/nanozuki/tabby.nvim"
passthru.as = "tabby"

[toggleterm]
fetch.github = "akinsho/toggleterm.nvim"
src.git = "https://github.com/akinsho/toggleterm.nvim"
passthru.as = "toggleterm"

[treewalker]
fetch.github = "aaronik/treewalker.nvim"
src.git = "https://github.com/aaronik/treewalker.nvim"
passthru.as = "treewalker"

[vim-fugitive]
fetch.github = "tpope/vim-fugitive"
src.git = "https://github.com/tpope/vim-fugitive"
passthru.as = "fugitive"

[vim-startuptime]
fetch.github = "dstein64/vim-startuptime"
src.git = "https://github.com/dstein64/vim-startuptime"
passthru.as = "startuptime"

[yosu-nvim]
fetch.github = "comfysage/yosu.nvim"
src.git = "https://github.com/comfysage/yosu.nvim"
passthru.as = "yosu"

[zk-nvim]
fetch.github = "mickael-menu/zk-nvim"
src.git = "https://github.com/mickael-menu/zk-nvim"
